version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vglazasmotri/kittygram_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    env_file: .env
    image: vglazasmotri/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: vglazasmotri/kittygram_gateway
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${HTTP_PORT}"
    volumes:
      - static:/staticfiles
      - media:/app/media/